# demo.aws_ec2.yml
plugin: aws_ec2
regions:
  - eu-central-1

keyed_groups:
  # add hosts to tag_Name_value groups for each aws_ec2 host's tags.Name variable
  - key: tags.Name
    prefix: tag_Name_
    separator: ""
  - key: tags.Type
    prefix: tag_Type_
    separator: ""

#hostnames:
#  - tag:Environment=Demo,type=itsm-db  # return specific hosts only

#plugin: aws_rds
#regions:
#  - eu-central-1
