---

- name: upgrade all packages
  yum:
    name: '*'
    state: latest
  become: yes

# 3858(  3858) 12/04/2018 10:03:54 [JGRP00014] Der send Puffer des Sockets DatagramSocket wurde auf 640KB gesetzt, aber das Betriebssystem stellt nur 212,99KB zur Verfuegung. Dies koennte zu Performanzproblemen fuehren. Bitte setzen Sie den max send Puffer im Betriebssystem korrekt (z.B. net.core.wmem_max unter Linux)
# 3858(  3858) 12/04/2018 10:03:54 [JGRP00014] Der receive Puffer des Sockets DatagramSocket wurde auf 20MB gesetzt, aber das Betriebssystem stellt nur 212,99KB zur Verfuegung. Dies koennte zu Performanzproblemen fuehren. Bitte setzen Sie den max receive Puffer im Betriebssystem korrekt (z.B. net.core.rmem_max unter Linux)
# 3858(  3858) 12/04/2018 10:03:54 [JGRP00014] Der send Puffer des Sockets MulticastSocket wurde auf 640KB gesetzt, aber das Betriebssystem stellt nur 212,99KB zur Verfuegung. Dies koennte zu Performanzproblemen fuehren. Bitte setzen Sie den max send Puffer im Betriebssystem korrekt (z.B. net.core.wmem_max unter Linux)
# 3858(  3858) 12/04/2018 10:03:54 [JGRP00014] Der receive Puffer des Sockets MulticastSocket wurde auf 25MB gesetzt, aber das Betriebssystem stellt nur 212,99KB zur Verfuegung. Dies koennte zu Performanzproblemen fuehren. Bitte setzen Sie den max receive Puffer im Betriebssystem korrekt (z.B. net.core.rmem_max unter Linux)
- name: change rmem buffer size
  command: sysctl -w net.core.rmem_max=8388608
  become: yes

- name: change wmem buffer size
  command: sysctl -w net.core.wmem_max=8388608
  become: yes

- name: change stateless kernel shmall size
  command: echo 134217728 >/proc/sys/kernel/shmall
  become: yes

- name: change stateless kernel shmmax size
  command: echo 134217728 >/proc/sys/kernel/shmmax
  become: yes

- name: change stateful kernel system settings
  blockinfile:
    path: /etc/sysctl.d/100-sm.conf
    create: yes
    block: |
      kernel.shmall = 134217728
      kernel.shmmax = 134217728
  become: yes
