---

tomcat_user: tomcat
tomcat_group: tomcat

tomcat_url: http://mirror.checkdomain.de/apache/tomcat/tomcat-8/v8.5.38/bin/apache-tomcat-8.5.38.tar.gz
tomcat_archive: apache-tomcat-8.5.38.tar.gz
tomcat_temp: /tmp
tomcat_path: /opt/tomcat
