---

tomcat_user: tomcat
tomcat_group: tomcat

webtier_target: /tmp
tomcat_webtier_path: /opt/tomcat/webapps
s3_bucket: itsm-classic-src
s3_webtier_path: itsm
s3_webtier_archive: webtier-9.62.war
deploy_path: /opt/tomcat/webapps/webtier
webxml_path: /opt/tomcat/webapps/webtier/WEB-INF/web.xml
sm_serverHost: localhost
remote_src: yes
