- name: create languagepack installdir
  file: path={{ install_filepath }} state=directory mode=0755 owner={{ install_user }}
  tags: prepare
  become: yes

- name: copy LanguagePack Archive from S3
  aws_s3:
    bucket: "{{ s3_bucket }}"
    object: "{{ s3_bin_path }}/{{ languagepack_bin }}"
    dest: "{{ install_filepath }}/{{ languagepack_bin }}"
    mode: get

- name: Unarchive languagepack Archive
  unarchive:
    src: "{{ install_filepath }}/{{ languagepack_bin }}"
    dest: "{{ install_filepath }}"
    mode: 0755
    owner: "{{ install_user }}"
    remote_src: yes
  tags: prepare
  become: yes

- name: chmod Installation Files
  file:
    path: "{{ install_bin_path }}/{{ install_bin }}"
    mode: 0777
  tags: prepare
  become: yes

- name: install languagepack
  expect:
    command: "{{ install_bin_path }}/{{ install_bin }} -i console"
    responses:
      'CHOOSE LOCALE BY NUMBER:' : '1'
      'DR\ÜCKEN SIE DIE EINGABETASTE, UM FORTZUFAHREN:' : ''
      'SIND SIE MIT DEN BEDINGUNGEN DIESES LIZENZVERTRAGS EINVERSTANDEN? \(J/N\):' : 'J'
      'GEBEN SIE EINEN ABSOLUTEN PFAD EIN, ODER DR\ÜCKEN SIE DIE EINGABETASTE, UM DIE STANDARDEINSTELLUNG ZU \ÜBERNEHMEN:' : ''
      'DR\ÜCKEN SIE DIE EINGABETASTE, UM DEN INSTALLER ZU BEENDEN:' : ''
    timeout: 90
  tags: install
