---

# - name: install Tomcat for Service Manger Webtier
#   yum:
#     name:
#        - tomcat
#     state: present
#   tags: tomcat
#   become: yes
#
- name: Create deploy folder directory
  file:
    path: "{{ deploy_path }}"
    state: directory
    mode: 0755
    owner: "{{ tomcat_user}}"
    group: "{{ tomcat_group }}"
  become: yes


- name: Delete tomcat default apps
  file:
    path: "{{ item }}"
    state: absent
  become: yes
  with_items:
    - "{{ tomcat_webtier_path }}/docs"
    - "{{ tomcat_webtier_path }}/examples"
    - "{{ tomcat_webtier_path }}/host-manager"
    - "{{ tomcat_webtier_path }}/manager"
    - "{{ tomcat_webtier_path }}/ROOT"

- name: copy webtier Archive from S3
  aws_s3:
    bucket: "{{ s3_bucket }}"
    object: "{{ s3_webtier_path }}/{{ s3_webtier_archive }}"
    # version: 48c9ee5131af7a716edc22df9772aa6f
    dest: "{{ webtier_target }}/{{ s3_webtier_archive }}"
    validate_certs: no
    mode: get

- name: Unarchive webtier Archive
  unarchive:
    src: "{{ webtier_target }}/{{ s3_webtier_archive }}"
    dest: "{{ deploy_path }}"
    mode: 0755
    owner: "{{ tomcat_user}}"
    group: "{{ tomcat_group }}"
    remote_src: "{{ remote_src }}"
  tags: prepare
  become: yes
  notify: restart tomcat
