---

- name: install python module botocore
  pip:
    name: botocore
    state: latest
  tags: prepare
  become: yes

- name: install python module boto
  pip:
    name: boto3
    state: latest
  tags: prepare
  become: yes

- name: install Tomcat for Service Manger Webtier
  yum:
    name:
       - tomcat
    state: present
  tags: tomcat
  become: yes

- name: copy webtier Archive from S3
  aws_s3:
    bucket: "{{ s3.bucket }}"
    object: "{{ s3.webtier_path }}/{{ s3.webtier_archive }}"
    # version: 48c9ee5131af7a716edc22df9772aa6f
    dest: "{{ itsm_web.webtier_target }}/{{ s3.webtier_archive }}"
    mode: get

- name: Unarchive webtier Archive
  unarchive: src={{ itsm_web.webtier_target }}/{{ s3.webtier_archive }} dest={{ itsm_web.webtier_path }} mode=0755 owner={{ tomcat_user}} group={{ tomcat_group }}
  tags: prepare
  become: yes

# - name: Copy webtier Archive and Unarchive it
#   unarchive:
#     src: "{{ itsm_web.webtier_archive }}"
#     dest: "{{ itsm_web.webtier_path }}"
#     mode: "0755"
#     owner: "{{ tomcat_user }}"
#     group: "{{ tomcat_group }}"
#   tags: webapp
#   become: yes

#keytool -genkey -noprompt \
# -alias alias1 \
# -dname "CN=mqttserver.ibm.com, OU=ID, O=IBM, L=Hursley, S=Hants, C=GB" \
# -keystore keystore \
# -storepass password \
# -keypass password

- name: generate ssl truststore
  command: keytool -genkey -keyalg RSA -noprompt -alias tomcat -dname "CN=servicemanager, OU=vagrant, O=DB, L=Franfurt, S=Hessen, C=DE" -keystore "{{ tomcat.keystore }}" -storepass changeit -keypass changeit
  become: yes

- name: copy server.xml with ssl activated
  copy:
    src: server.xml
    dest: "{{ tomcat.config_path }}"
    #owner: "{{ tomcat_user }}"
    owner: root
    group: "{{ tomcat_group }}"
    mode: 0755
  become: yes
  notify: restart tomcat
