---

- name: configure sp-initiated sso
  template:
    src: web.xml.j2
    dest: "{{ tomcat_webtier_path }}{{ idm_webinf_path }}"
    owner: "{{ tomcat_user }}"
    #owner: root
    group: "{{ tomcat_group }}"
    mode: 0755
  become: yes
  #notify: restart tomcat

- name: set sso domain
  template:
    src: hpssoConfig.xml.j2
    dest: "{{ tomcat_webtier_path }}{{ idm_webinf_path }}"
    owner: "{{ tomcat_user }}"
    #owner: root
    group: "{{ tomcat_group }}"
    mode: 0755
  become: yes
  #notify: restart tomcat

- name: spring saml config
  template:
    src: applicationContext-saml.xml
    dest: "{{ tomcat_webtier_path }}{{ idm_webinf_path }}/spring"
    owner: "{{ tomcat_user }}"
    #owner: root
    group: "{{ tomcat_group }}"
    mode: 0755
  become: yes
  #notify: restart tomcat

- name: spring v0 config
  template:
    src: applicationContext-v0.xml
    dest: "{{ tomcat_webtier_path }}{{ idm_webinf_path }}/spring"
    owner: "{{ tomcat_user }}"
    #owner: root
    group: "{{ tomcat_group }}"
    mode: 0755
  become: yes
  #notify: restart tomcat

- name: copy hpe tenant for sso
  template:
    src: com.hpe.tenant1__1.3.2.1__Add_Update_Saml_Configuration.json
    dest: "{{ tomcat_webtier_path }}{{ idm_webinf_path }}/classes/seeded"
    owner: "{{ tomcat_user }}"
    #owner: root
    group: "{{ tomcat_group }}"
    mode: 0755
  become: yes
  #notify: restart tomcat

- name: generate SAML keystore
  command: keytool -genkey -keyalg RSA -noprompt -alias itsmsaml -keystore samlKeystore.jks -storepass changeit -validity 1080 -keysize 2048
    chdir: "{{ tomcat_webtier_path }}{{ idm_webinf_path }}/classes/security"
  become: yes

- name: copy hpe tenant for sso
  file:
    src: log4j.properties
    dest: "{{ tomcat_webtier_path }}{{ idm_webinf_path }}/classes"
    owner: "{{ tomcat_user }}"
    #owner: root
    group: "{{ tomcat_group }}"
    mode: 0755
  become: yes
  #notify: restart tomcat
