---

- name: Ensure group "tomcat" exists
  group:
    name: tomcat
    state: present
  become: yes

- name: create user tomcat
  user:
    name: tomcat
    comment: tomcat default user
    group: tomcat
    state: present
  become: yes

- name: install openjdk 8
  yum:
    name:
       - java-1.8.0-openjdk
    state: present
  tags: openjdk
  become: yes

- name: create tomcat directory
  file:
    path: "{{ tomcat_path }}"
    state: directory
    mode: 0755
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
  tags: prepare
  become: yes

- name: download tomcat
  get_url:
    url: "{{ tomcat_url }}"
    dest: /tmp/tomcat.tar.gz

- name: Unarchive tomcat install
  unarchive:
    src: /tmp/tomcat.tar.gz
    dest: "{{ tomcat_path }}"
    mode: 0755
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    extra_opts: [--strip-components=1]
    remote_src: yes
  tags: prepare
  become: yes
