---

- name: Ensure group "tomcat" exists
  group:
    name: tomcat
    state: present
  become: yes

- name: create user tomcat
  user:
    name: tomcat
    comment: tomcat default user
    group: tomcat
    state: present
  become: yes

- name: install openjdk 8
  yum:
    name:
       - java-1.8.0-openjdk
    state: present
  tags: openjdk
  become: yes

- name: create tomcat directory
  file:
    path: "{{ tomcat_path }}"
    state: directory
    mode: 0755
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
  tags: prepare
  become: yes

- name: download tomcat
  get_url:
    url: "{{ tomcat_url }}"
    dest: /tmp/tomcat.tar.gz

- name: Unarchive tomcat install
  unarchive:
    src: /tmp/tomcat.tar.gz
    dest: "{{ tomcat_path }}"
    mode: 0755
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    extra_opts: [--strip-components=1]
    remote_src: yes
  tags: prepare
  become: yes

- name: add tomcat.service
  template:
    src: tomcat.service.j2
    dest: "{{ tomcat_service_path }}/{{ tomcat_service_file }}"
    mode: 0755
  become: true

- name: install tomcat as service
  shell: systemctl daemon-reload
  become: true

- name: enable tomcat service
  shell: systemctl enable tomcat.service
  become: true

- name: generate ssl truststore
  command: keytool -genkey -keyalg RSA -noprompt -alias tomcat -dname "CN=servicemanager, OU=vagrant, O=DB, L=Franfurt, S=Hessen, C=DE" -keystore "{{ tomcat_keystore }}" -storepass changeit -keypass changeit
  become: yes

- name: change owner keystore
  file:
    path: "{{ tomcat_keystore }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    state: file
  become: yes

- name: copy server.xml with ssl activated
  copy:
    src: server.xml
    dest: "{{ tomcat_config_path }}"
    #owner: "{{ tomcat_user }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: 0755
  become: yes
  notify: restart tomcat
