---

- name: install Python Module Manager
  yum:
    name: python2-pip
    state: latest
  tags: prepare
  become: yes

- name: install python module pexpect
  pip:
    name: pexpect
    state: latest
  tags: prepare
  become: yes
  # There is an error at installation of the module which can ignored
  #ignore_errors: yes

- name: install python module botocore
  pip:
    name: botocore
    state: latest
  tags: prepare
  become: yes

- name: install python module boto
  pip:
    name: boto3
    state: latest
  tags: prepare
  become: yes

- name: create sm installdir
  file: path={{ installation.filepath }} state=directory mode=0755 owner={{ install_user }}
  tags: prepare
  become: yes

- name: copy ITSM Archive from S3
  aws_s3:
    bucket: gregulla.itsm.stuff
    object: "{{ s3.bin_path }}/{{ source.sm_bin }}"
    # version: 48c9ee5131af7a716edc22df9772aa6f
    dest: "{{ installation.filepath }}/{{ source.sm_bin }}"
    mode: get

- name: Unarchive ITSM Archive
  unarchive: src={{ installation.filepath }}/{{ source.sm_bin }} dest={{ installation.filepath }} mode=0755 owner={{ install_user }}
  tags: prepare
  become: yes

- name: chmod Installation Files
  file:
    path: "{{ installation.bin_path }}/{{ installation.bin }}"
    mode: 0777
  tags: prepare
  become: yes

- name: create target itsm directory
  file:
    path: "{{ installation.install_dir }}"
    state: directory
    owner: "{{ install_user }}"
    mode: 0755
  tags: prepare
  become: yes

- name: install itsm
  expect:
    command: "{{ installation.bin_path }}/{{ installation.bin }} -i console"
    responses:
      'PRESS \<ENTER\> TO CONTINUE:' : ''
      'DO YOU ACCEPT THE TERMS OF THIS LICENSE AGREEMENT?' : 'Y'
      'ENTER AN ABSOLUTE PATH, OR PRESS \<ENTER\> TO ACCEPT THE DEFAULT' : "{{ installation.install_server_dir }}"
      'IS THIS CORRECT?' : 'Y'
      'PRESS \<ENTER\> TO EXIT THE INSTALLER' : ''
    timeout: 90
  tags: install

- name: add sm.ini
  copy:
    src: sm.ini
    dest: "{{ installation.install_server_dir }}/RUN"
    owner: "{{ install_user }}"
    mode: 0755

# work only on redhat images
#- name: install openjdk per internal script
#  command: "{{ installation.install_server_dir }}/installOpenJDK.sh -i4sm"
#  tags: prepare
#  become: yes

- name: link jre in sm installation
  command: "{{ installation.install_server_dir }}/RUN/setupLinks.sh jre"
  environment:
    JAVA_HOME: "{{ java.home }}"
  tags: install

- name: create patches installdir
  file: path={{ patch.patch_path }} state=directory mode=0755 owner={{ install_user }}
  tags: patch
  become: yes

#- name: copy itsm patch and unarchive it
#  unarchive: src={{ patch.patch_file }} dest={{ patch.patch_path }} mode=0755 owner={{ install_user }}
#  tags: patch
#  become: yes

- name: copy ITSM Patch from S3
  aws_s3:
    bucket: gregulla.itsm.stuff
    object: "{{ s3.bin_path }}/{{ patch.patch_file }}"
    # version: 48c9ee5131af7a716edc22df9772aa6f
    dest: "{{ patch.patch_path }}/{{ patch.patch_file }}"
    mode: get

- name: unarchive patch
  unarchive:
    src: "{{ patch.patch_path }}/{{ patch.patch_file }}"
    dest: "{{ patch.patch_path }}"
    mode: 0755
    owner: "{{ install_user }}"
    remote_src: yes
  tags: patch
  become: yes

- name: unarchive patchfile
  unarchive:
    src: "{{ patch.patch_path }}/{{ patch.patch_patch }}"
    dest: "{{ patch.patch_path }}"
    mode: 0755
    owner: "{{ install_user }}"
    remote_src: yes
  tags: patch
  become: yes

- name: create patches backupdir
  file: path={{ patch.patch_backup }} state=directory mode=0755 owner={{ install_user }}
  tags: patch
  become: yes

# - name: change owner server_dir to install_user
#   file:
#     path: "{{ installation.install_server_dir }}"
#     owner: "{{ install_user }}"
#     recurse: yes
#   tags: prepare
#   become: yes

- name: create logdir
  file: path="{{ installation.install_server_dir }}/logs" state=directory mode=0755 owner={{ install_user }}
  tags: patch

- name: install itsm patch
  expect:
    command: "{{ patch.patch_path }}/{{ patch.patch_cmd }}"
    chdir: "{{ installation.install_server_dir }}"
    responses:
      'SM Server installation directory' : "{{ installation.install_server_dir }}"
      'SM Server backup directory' : "{{ patch.patch_backup }}"
      'ENTER AN ABSOLUTE PATH, OR PRESS \<ENTER\> TO ACCEPT THE DEFAULT' : "{{ installation.install_server_dir }}"
      'IS THIS CORRECT?' : 'Y'
      'PRESS \<ENTER\> TO EXIT THE INSTALLER' : ''
  tags: patch

- name: create temporary license
  shell: "{{ installation.install_server_dir }}/RUN/sm -instanton"
  args:
    executable: /bin/bash
    chdir: "{{ installation.install_server_dir }}/RUN"
  tags: license

  # [vagrant@localhost Server]$ ./configure -consolemode
  # WARNING: This program is meant for out-of-box system configuration.
  # It will overwrite your current settings in sm.ini.
  # Please backup your sm.ini file.
  # Enter httpPort (Current value - 13080 ):
  # Choose Database Type:
  # (0) Oracle 12c
  # (1) PostgreSQL (Current value - 1 ):
  # Enter Database name (Current value - host=localhost port=5432 dbname=smdb ):
  # Enter SQL user (Current value -  ):smuser
  # Enter SQL password (Current value -  ):smpassw0rd
  # Enter Postgres Schema (Current value - sm ):sm
  # Case Insensitive?(Y or N) (Current value - Y ):N
  # Updating new configuration to sm.ini...
  # Validating SQL connectivity.... Please wait....

- name: configure itsm
  expect:
    command: "{{ installation.install_server_dir }}/configure -consolemode"
    chdir: "{{ installation.install_server_dir }}"
    responses:
      'Enter httpPort' : "{{ installation.server_port }}"
      'Choose Database Type' : '1'
      'Enter Database name' : 'host={{ db.server_dbhost }} port={{ installation.server_dbport }} dbname={{ db.dbname }}'
      'Enter SQL user' : '{{ db.dbuser }}'
      'Enter SQL password' : '{{ db.dbpassword }}'
      #'Enter Postgres Schema': '{{ db.dbschema }}'
      'Enter Postgres Schema': ''
      'Case Insensitive?': 'N'
      'Do you wish to load Service Manager application and demo data to the Database': 'Y'
  # there are some ignorable errors in the output
  ignore_errors: yes
  tags: configure

- name: start sm
  shell: "{{ installation.install_server_dir }}/RUN/smstart"
  args:
    executable: /bin/bash
    chdir: "{{ installation.install_server_dir }}/RUN"
  tags: start

# - name: shutdown sm
#   shell: "{{ installation.install_server_dir }}/RUN/sm -shutdown"
#   args:
#     executable: /bin/bash
#     chdir: "{{ installation.install_server_dir }}/RUN"
#   tags: license
