---

- name: ensure database is created
  postgresql_db: name="{{ db.dbname }}"
    login_host: "{{ db_server_dbhost }}"
  become: true
  become_user: "{{ postgres_user }}"

- name: ensure user has access to database
  postgresql_user: db="{{ sm_dbname }}" name="{{ sm_dbuser }}" password="{{ sm_dbpassword }}" priv=ALL
  become: true
  become_user: "{{ postgres_user }}"

- name: ensure user does not have unnecessary privilege
  postgresql_user: name="{{ db.dbuser }}" role_attr_flags=NOSUPERUSER,NOCREATEDB
  become: true
  become_user: "{{ postgres_user }}"

- name: ensure no other user can access the database
  postgresql_privs: db="{{ db.dbname }}" role=PUBLIC type=database priv=ALL state=absent
  become: true
  become_user: "{{ postgres_user }}"

- name: create sm schema
  postgresql_schema:
    database: "{{ sm_dbname }}"
    name: "{{ sm_dbschema }}"
    owner: "{{ sm_dbuser }}"
  become: true
  become_user: "{{ postgres_user }}"
  #notify: restart postgresql
