---

- name: copy idm from S3
  aws_s3:
    bucket: "{{ s3_bucket }}"
    object: "{{ s3_idm_path }}/{{ s3_idm_archive }}"
    # version: 48c9ee5131af7a716edc22df9772aa6f
    dest: "{{ webtier_target }}/{{ s3_idm_archive }}"
    mode: get
  tags: idm_install

- name: Create deploy folder directory
  file:
    path: "{{ idm_deploy_path }}"
    state: directory
    mode: 0755
    owner: "{{ tomcat_user}}"
    group: "{{ tomcat_group }}"
  become: yes

- name: unarchive idm war
  unarchive:
    src: "{{ webtier_target }}/{{ s3_idm_archive }}"
    dest: "{{ idm_deploy_path }}"
    mode: 0755
    owner: "{{ tomcat_user}}"
    group: "{{ tomcat_group }}"
    remote_src: "{{ remote_src }}"
  tags: idm_install
  become: yes
  #notify: restart tomcat
