---
# file: webservers.yml
- hosts: all
  vars:
    install_user: ec2-user
    java_download_url: https://rpmfind.net/linux/centos/7.6.1810/updates/x86_64/Packages/java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.i686.rpm
    java_home: /usr/lib/jvm/jre
    sm_serverHost: internal-itsm-EC2El-RCCD7NEON9LZ-1615163355.eu-central-1.elb.amazonaws.com

  roles:
    - common
#    - jdk
    - sm-webtier

  environment:
    http_proxy: http://webproxy.comp.db.de:8080
    https_proxy: http://webproxy.comp.db.de:8080
