---
# packer playbook
- hosts: all
  vars:
    s3_bucket: itsm-classic-src
    s3_webtier_path: Hersteller_Software_Patch
    s3_webtier_archive: sm9.62.0016_Web_Tier.zip
    install_user: ec2-user
    java_download_url: https://rpmfind.net/linux/centos/7.6.1810/updates/x86_64/Packages/java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.i686.rpm
    java_home: /usr/lib/jvm/jre
    sm_serverHost: internal-itsm-EC2El-RCCD7NEON9LZ-1615163355.eu-central-1.elb.amazonaws.com
    remote_src: yes

  roles:
# create concrete Instance
    # - get-rdsfacts
    # - sm-server-configure

# create AMI
    - prepare-ansible
    - tomcat
    - sm-webtier

  environment:
    http_proxy: http://webproxy.comp.db.de:8080
    https_proxy: http://webproxy.comp.db.de:8080
