---
# file: webservers.yml
- hosts: all
  vars:
#    proxy_env:
#      http_proxy: http://webproxy.comp.db.de:8080
#      https_proxy: http://webproxy.comp.db.de:8080
    ansible_ssh_private_key_file: ~/.ssh/AWSSierra.pem
    install_user: ec2-user
    sm_dbname: smdb
    sm_dbschema: sm
    sm_dbuser: smuser
    sm_dbpassword: smpassw0rd
    sm_postgres_user: postgres
    #sm_server_dbhost: itsm-db.ch1znfaihylb.eu-central-1.rds.amazonaws.com
    sm_server_dbport: 5432
    java:
      home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181-7.b13.el7.i386/jre
      source:
        #download_url: https://rpmfind.net/linux/centos/7.6.1810/os/x86_64/Packages/java-1.8.0-openjdk-headless-1.8.0.181-7.b13.el7.i686.rpm
        download_url: https://rpmfind.net/linux/centos/7.6.1810/updates/x86_64/Packages/java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.i686.rpm
        download_folder: /tmp
        java_archive: jdk-8u192-linux-x64.tar.gz
        #download_cmd: "wget --continue --no-check-certificate -O /tmp/{{ java.source.java_archive }} --header \"Cookie: oraclelicense=a\" {{ java.source.install_file }}"
        #install_rpm: https://download.oracle.com/otn-pub/java/jdk/8u191-b12/2787e4a523244c269598db4e85c51e0c/jre-8u191-linux-i586.rpm
        #install_wget_rpm: wget --continue --no-check-certificate -O jdk-8u191-linux-x64.rpm --header "Cookie: oraclelicense=a" https://download.oracle.com/otn-pub/java/jdk/8u191-b12/2787e4a523244c269598db4e85c51e0c/jre-8u191-linux-i586.rpm
        #install_wget_tar: wget --continue --no-check-certificate -O jdk-8u191-linux-x64.tar.gz --header "Cookie: oraclelicense=a" https://download.oracle.com/otn-pub/java/jdk/8u191-b12/2787e4a523244c269598db4e85c51e0c/jre-8u191-linux-i586.tar.gz
        #install_wget_tar: wget --continue --no-check-certificate -O jdk-8u192-linux-x64.tar.gz --header "Cookie: oraclelicense=a" https://download.oracle.com/otn-pub/java/jdk/8u192-b12/750e1c8617c5452694857ad95c3ee230/jre-8u192-linux-i586.tar.gz
      installation:
        install_path: /opt/java
        java_dir: jre1.8.0_192
        server_port: 13080

  roles:
    - common
    - get-rdsfacts
#    - sm-postgres
#    - prepare-postgres
#    - jdk
#    - sm-server
    - sm-server-configure
#    - sm-webtier
