---
# file: webservers.yml
- hosts: all
  vars:
#    proxy_env:
#      http_proxy: http://webproxy.comp.db.de:8080
#      https_proxy: http://webproxy.comp.db.de:8080
    ansible_ssh_private_key_file: ~/.ssh/AWSSierra.pem
    install_user: ec2-user
    sm_dbname: smdb
    sm_dbschema: sm
    sm_dbuser: smuser
    sm_dbpassword: smpassw0rd
    sm_postgres_user: postgres
    sm_server_dbname: smdb
    #sm_server_dbhost: itsm-db.ch1znfaihylb.eu-central-1.rds.amazonaws.com
    sm_server_dbport: 5432
    production_mode: false

  roles:
    - common
    - get-rdsfacts
#    - sm-postgres
#    - prepare-postgres
#    - jdk
#    - sm-server
    - sm-server-configure
#    - sm-webtier
