---
# file: webservers.yml
- hosts: all
  vars:
    install_user: ec2-user
    sm_dbschema: sm
    sm_dbuser: postgres
    java_home: /usr/lib/jvm/jre
    java_download_url: https://rpmfind.net/linux/centos/7.6.1810/updates/x86_64/Packages/java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.i686.rpm
    java_download_folder: /tmp
    java_install_path: /opt/java
    java_dir: jre1.8.0_192
    sm_server_port: 13080
    postgres_user: postgres
    smini_enable_ldap: 0
    remote_src: yes

  roles:
# create concrete Instance
    # - get-rdsfacts
    # - sm-server-configure

# create AMI
    - prepare-ansible
    - common
    - sm-server
    - sm-server-patch
    - languagepack

  # environment:
  #   http_proxy: http://webproxy.comp.db.de:8080
  #   https_proxy: http://webproxy.comp.db.de:8080
