---

- name: load secrets into playbook
  include_vars: secrets.yml
  
- name: add sm.ini
  template:
    src: sm.ini.j2
    dest: "{{ sm_install_server_dir }}/RUN/sm.ini"
    owner: "{{ install_user }}"
    force: yes
    mode: 0755

- name: add sm.cfg
  copy:
    src: sm.cfg
    dest: "{{ sm_install_server_dir }}/RUN/sm.cfg"
    owner: "{{ install_user }}"
    force: yes
    mode: 0755

- name: create temporary license
  shell: "{{ sm_install_server_dir }}/RUN/sm -instanton"
  args:
    executable: /bin/bash
    chdir: "{{ sm_install_server_dir }}/RUN"
  tags: license

- name: unlock database
  shell: "{{ sm_install_server_dir }}/RUN/sm -unlockdatabase"
  args:
    executable: /bin/bash
    chdir: "{{ sm_install_server_dir }}/RUN"
  tags: unlock_database

- name: start sm
  shell: "{{ sm_install_server_dir }}/RUN/smstart"
  args:
    executable: /bin/bash
    chdir: "{{ sm_install_server_dir }}/RUN"
  tags: start_sm
