---

- name: create java installdir
  file: path={{ java.installation.install_path }} state=directory
  tags: prepare
  become: yes

- name: install glibc for java
  yum:
    name: glibc.i686
  tags: prepare
  become: yes

- name: install openjdk 32bit
  yum:
    name: "{{ java.source.download_url }}"
  tags: prepare
  become: yes

#- name: Make Java available for system
#  command: 'alternatives --install "/usr/bin/java" "java" "{{java.installation.install_path}}/{{java.installation.java_dir}}/bin/java" 2000'
#  become: yes

#- name: Clean up java installation files
#  file: state=absent path="{{ java.source.download_folder }}/{{ java.source.java_archive }}"
